### ISSUE TITLE
Your awesome presentation 🥇

### ISSUE THREAD

**Issue by th-zf** [BCX22-Group1/ecal-carla#1]
[Posted on all  of your repos ;)]

Hi Team 1,
thanks your participation, engagement and spirit for the hackathon. I hope you had great time hacking 💯 . As a coach, I can tell you all did a great job. On your developed solutions, presentations and the pitches.

Here is my request: Can you please share the latest version of your presentation? 

- You can upload it to your repository.
- Or share it with me (thomas.hochstrasser@zf.com). I will make them available on an another repository in the 'https://github.com/Eclipse-SDV-Hackathon-BCX' repository.

If multiple files are required.  Please zip them together 👍 .

Best regards,
Thomas Hochstrasser

**Comment by PeterK311** [comment]
Hi Thomas Hochstrasser,

we did not forget about your request. I have sent you the link via mail. :) 
Thanks for your interest in our presentation. Please find the shareable link attached: 

https://www.linkedin.com/smart-links/AQEGrDMENLOlng/2704af7f-ae37-4fec-9311-c103b5795142

Feel free to contact us in case you have any questions.


Best Regards
Peter

**Comment by th-zf** [comment]
Sorry for the late response. Thank you very much. I was able to download it.

Best regards, Thomas
